DROP TABLE IF EXISTS activity_logs;
DROP TABLE IF EXISTS bank_balance;
DROP TABLE IF EXISTS settings;
DROP TABLE IF EXISTS budget_lines;
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS siigo_configs;
DROP TABLE IF EXISTS allowed_domains;
DROP TABLE IF EXISTS users;
